//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubberduck.CodeAnalysis.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    public sealed partial class CodeInspectionDefaults : global::System.Configuration.ApplicationSettingsBase {
        
        private static CodeInspectionDefaults defaultInstance = ((CodeInspectionDefaults)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CodeInspectionDefaults())));
        
        public static CodeInspectionDefaults Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<CodeInspectionSettings xmlns:xsd=\"http:" +
            "//www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instanc" +
            "e\">\r\n  <CodeInspections>\r\n    <CodeInspection Name=\"AnnotationInIncompatibleComp" +
            "onentTypeInspection\" Severity=\"Warning\" InspectionType=\"RubberduckOpportunities\"" +
            " />\r\n    <CodeInspection Name=\"ApplicationWorksheetFunctionInspection\" Severity=" +
            "\"Suggestion\" InspectionType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspection" +
            " Name=\"ArgumentWithIncompatibleObjectTypeInspection\" Severity=\"Warning\" Inspecti" +
            "onType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspection Name=\"AssignedByValP" +
            "arameterInspection\" Severity=\"Warning\" InspectionType=\"CodeQualityIssues\" />\r\n  " +
            "  <CodeInspection Name=\"AssignmentNotUsedInspection\" Severity=\"Error\" Inspection" +
            "Type=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"AttributeValueOutOfSyncIn" +
            "spection\" Severity=\"Error\" InspectionType=\"RubberduckOpportunities\" />\r\n    <Cod" +
            "eInspection Name=\"BooleanAssignedInIfElseInspection\" Severity=\"Suggestion\" Inspe" +
            "ctionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ConstantNotUsedInspe" +
            "ction\" Severity=\"Warning\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspec" +
            "tion Name=\"DefaultMemberRequiredInspection\" Severity=\"Error\" InspectionType=\"Cod" +
            "eQualityIssues\" />\r\n    <CodeInspection Name=\"DefaultProjectNameInspection\" Seve" +
            "rity=\"Suggestion\" InspectionType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspe" +
            "ction Name=\"DefTypeStatementInspection\" Severity=\"Warning\" InspectionType=\"Langu" +
            "ageOpportunities\" />\r\n    <CodeInspection Name=\"DuplicatedAnnotationInspection\" " +
            "Severity=\"Error\" InspectionType=\"RubberduckOpportunities\" />\r\n    <CodeInspectio" +
            "n Name=\"EmptyCaseBlockInspection\" Severity=\"Hint\" InspectionType=\"CodeQualityIss" +
            "ues\" />\r\n    <CodeInspection Name=\"EmptyDoWhileBlockInspection\" Severity=\"Hint\" " +
            "InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"EmptyElseBlockI" +
            "nspection\" Severity=\"Hint\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspe" +
            "ction Name=\"EmptyForEachBlockInspection\" Severity=\"Hint\" InspectionType=\"CodeQua" +
            "lityIssues\" />\r\n    <CodeInspection Name=\"EmptyForLoopBlockInspection\" Severity=" +
            "\"Hint\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"EmptyIfB" +
            "lockInspection\" Severity=\"Hint\" InspectionType=\"CodeQualityIssues\" />\r\n    <Code" +
            "Inspection Name=\"EmptyMethodInspection\" Severity=\"Hint\" InspectionType=\"CodeQual" +
            "ityIssues\" />\r\n    <CodeInspection Name=\"EmptyModuleInspection\" Severity=\"Hint\" " +
            "InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"EmptyStringLite" +
            "ralInspection\" Severity=\"Suggestion\" InspectionType=\"LanguageOpportunities\" />\r\n" +
            "    <CodeInspection Name=\"EmptyWhileWendBlockInspection\" Severity=\"Hint\" Inspect" +
            "ionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"EncapsulatePublicField" +
            "Inspection\" Severity=\"Suggestion\" InspectionType=\"NamingAndConventionsIssues\" />" +
            "\r\n    <CodeInspection Name=\"ExcelMemberMayReturnNothingInspection\" Severity=\"War" +
            "ning\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ExcelUdfN" +
            "ameIsValidCellReferenceInspection\" Severity=\"Warning\" InspectionType=\"NamingAndC" +
            "onventionsIssues\" />\r\n    <CodeInspection Name=\"FunctionReturnValueAlwaysDiscard" +
            "edInspection\" Severity=\"Suggestion\" InspectionType=\"CodeQualityIssues\" />\r\n    <" +
            "CodeInspection Name=\"FunctionReturnValueDiscardedInspection\" Severity=\"Hint\" Ins" +
            "pectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"HostSpecificExpres" +
            "sionInspection\" Severity=\"Warning\" InspectionType=\"CodeQualityIssues\" />\r\n    <C" +
            "odeInspection Name=\"HungarianNotationInspection\" Severity=\"Suggestion\" Inspectio" +
            "nType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspection Name=\"IIfSideEffectIn" +
            "spection\" Severity=\"Error\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspe" +
            "ction Name=\"ImplementedInterfaceMemberInspection\" Severity=\"Warning\" InspectionT" +
            "ype=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ImplicitActiveSheetReferen" +
            "ceInspection\" Severity=\"Warning\" InspectionType=\"CodeQualityIssues\" />\r\n    <Cod" +
            "eInspection Name=\"ImplicitActiveWorkbookReferenceInspection\" Severity=\"Warning\" " +
            "InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ImplicitByRefMo" +
            "difierInspection\" Severity=\"Hint\" InspectionType=\"NamingAndConventionsIssues\" />" +
            "\r\n    <CodeInspection Name=\"ImplicitContainingWorkbookReferenceInspection\" Sever" +
            "ity=\"Warning\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"I" +
            "mplicitContainingWorksheetReferenceInspection\" Severity=\"Warning\" InspectionType" +
            "=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ImplicitDefaultMemberAccessIn" +
            "spection\" Severity=\"Warning\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeIns" +
            "pection Name=\"ImplicitlyTypedConstInspection\" Severity=\"Warning\" InspectionType=" +
            "\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ImplicitPublicMemberInspection" +
            "\" Severity=\"Hint\" InspectionType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspe" +
            "ction Name=\"ImplicitRecursiveDefaultMemberAccessInspection\" Severity=\"Suggestion" +
            "\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ImplicitUnbou" +
            "ndDefaultMemberAccessInspection\" Severity=\"Warning\" InspectionType=\"CodeQualityI" +
            "ssues\" />\r\n    <CodeInspection Name=\"ImplicitVariantReturnTypeInspection\" Severi" +
            "ty=\"Warning\" InspectionType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspection" +
            " Name=\"IndexedDefaultMemberAccessInspection\" Severity=\"Hint\" InspectionType=\"Nam" +
            "ingAndConventionsIssues\" />\r\n    <CodeInspection Name=\"IndexedRecursiveDefaultMe" +
            "mberAccessInspection\" Severity=\"Suggestion\" InspectionType=\"NamingAndConventions" +
            "Issues\" />\r\n    <CodeInspection Name=\"IndexedUnboundDefaultMemberAccessInspectio" +
            "n\" Severity=\"Warning\" InspectionType=\"NamingAndConventionsIssues\" />\r\n    <CodeI" +
            "nspection Name=\"IntegerDataTypeInspection\" Severity=\"Suggestion\" InspectionType=" +
            "\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"InvalidAnnotationInspectio" +
            "n\" Severity=\"Warning\" InspectionType=\"RubberduckOpportunities\" />\r\n    <CodeInsp" +
            "ection Name=\"IsMissingOnInappropriateArgumentInspection\" Severity=\"Error\" Inspec" +
            "tionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"IsMissingWithNonArgum" +
            "entParameterInspection\" Severity=\"Error\" InspectionType=\"CodeQualityIssues\" />\r\n" +
            "    <CodeInspection Name=\"KeywordsUsedAsMemberInspection\" Severity=\"Warning\" Ins" +
            "pectionType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspection Name=\"LineConti" +
            "nuationBetweenKeywordsInspection\" Severity=\"Error\" InspectionType=\"NamingAndConv" +
            "entionsIssues\" />\r\n    <CodeInspection Name=\"LineLabelNotUsedInspection\" Severit" +
            "y=\"Suggestion\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"" +
            "MemberNotOnInterfaceInspection\" Severity=\"Warning\" InspectionType=\"CodeQualityIs" +
            "sues\" />\r\n    <CodeInspection Name=\"MisleadingByRefInspection\" Severity=\"Warning" +
            "\" InspectionType=\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"MissingAn" +
            "notationArgumentInspection\" Severity=\"Error\" InspectionType=\"RubberduckOpportuni" +
            "ties\" />\r\n    <CodeInspection Name=\"MissingAttributeInspection\" Severity=\"Error\"" +
            " InspectionType=\"RubberduckOpportunities\" />\r\n    <CodeInspection Name=\"MissingM" +
            "emberAnnotationInspection\" Severity=\"Warning\" InspectionType=\"RubberduckOpportun" +
            "ities\" />\r\n    <CodeInspection Name=\"MissingModuleAnnotationInspection\" Severity" +
            "=\"Warning\" InspectionType=\"RubberduckOpportunities\" />\r\n    <CodeInspection Name" +
            "=\"ModuleScopeDimKeywordInspection\" Severity=\"Suggestion\" InspectionType=\"NamingA" +
            "ndConventionsIssues\" />\r\n    <CodeInspection Name=\"ModuleWithoutFolderInspection" +
            "\" Severity=\"Suggestion\" InspectionType=\"RubberduckOpportunities\" />\r\n    <CodeIn" +
            "spection Name=\"MoveFieldCloserToUsageInspection\" Severity=\"Suggestion\" Inspectio" +
            "nType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspection Name=\"MultilineParame" +
            "terInspection\" Severity=\"Warning\" InspectionType=\"NamingAndConventionsIssues\" />" +
            "\r\n    <CodeInspection Name=\"MultipleDeclarationsInspection\" Severity=\"Warning\" I" +
            "nspectionType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspection Name=\"Negativ" +
            "eLineNumberInspection\" Severity=\"Warning\" InspectionType=\"CodeQualityIssues\" />\r" +
            "\n    <CodeInspection Name=\"NonBreakingSpaceIdentifierInspection\" Severity=\"Warni" +
            "ng\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"NonReturnin" +
            "gFunctionInspection\" Severity=\"Error\" InspectionType=\"CodeQualityIssues\" />\r\n   " +
            " <CodeInspection Name=\"ObjectVariableNotSetInspection\" Severity=\"Error\" Inspecti" +
            "onType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ObjectWhereProcedureIsR" +
            "equiredInspection\" Severity=\"Error\" InspectionType=\"CodeQualityIssues\" />\r\n    <" +
            "CodeInspection Name=\"ObsoleteCallingConventionInspection\" Severity=\"Error\" Inspe" +
            "ctionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ObsoleteCallStatemen" +
            "tInspection\" Severity=\"Suggestion\" InspectionType=\"LanguageOpportunities\" />\r\n  " +
            "  <CodeInspection Name=\"ObsoleteCommentSyntaxInspection\" Severity=\"Suggestion\" I" +
            "nspectionType=\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"ObsoleteErro" +
            "rSyntaxInspection\" Severity=\"Suggestion\" InspectionType=\"LanguageOpportunities\" " +
            "/>\r\n    <CodeInspection Name=\"ObsoleteGlobalInspection\" Severity=\"Suggestion\" In" +
            "spectionType=\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"ObsoleteLetSt" +
            "atementInspection\" Severity=\"Suggestion\" InspectionType=\"LanguageOpportunities\" " +
            "/>\r\n    <CodeInspection Name=\"ObsoleteMemberUsageInspection\" Severity=\"Warning\" " +
            "InspectionType=\"RubberduckOpportunities\" />\r\n    <CodeInspection Name=\"ObsoleteT" +
            "ypeHintInspection\" Severity=\"Suggestion\" InspectionType=\"LanguageOpportunities\" " +
            "/>\r\n    <CodeInspection Name=\"ObsoleteWhileWendStatementInspection\" Severity=\"Su" +
            "ggestion\" InspectionType=\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"O" +
            "nErrorGoToMinusOneInspection\" Severity=\"Suggestion\" InspectionType=\"LanguageOppo" +
            "rtunities\" />\r\n    <CodeInspection Name=\"OnLocalErrorInspection\" Severity=\"Sugge" +
            "stion\" InspectionType=\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"Opti" +
            "onBaseInspection\" Severity=\"Hint\" InspectionType=\"NamingAndConventionsIssues\" />" +
            "\r\n    <CodeInspection Name=\"OptionExplicitInspection\" Severity=\"Error\" Inspectio" +
            "nType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspection Name=\"ParameterCanBeB" +
            "yValInspection\" Severity=\"Suggestion\" InspectionType=\"LanguageOpportunities\" />\r" +
            "\n    <CodeInspection Name=\"ParameterNotUsedInspection\" Severity=\"Suggestion\" Ins" +
            "pectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ProcedureCanBeWrit" +
            "tenAsFunctionInspection\" Severity=\"Suggestion\" InspectionType=\"LanguageOpportuni" +
            "ties\" />\r\n    <CodeInspection Name=\"ProcedureNotUsedInspection\" Severity=\"Sugges" +
            "tion\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"Procedure" +
            "RequiredInspection\" Severity=\"Error\" InspectionType=\"CodeQualityIssues\" />\r\n    " +
            "<CodeInspection Name=\"PublicControlFieldAccessInspection\" Severity=\"Hint\" Inspec" +
            "tionType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspection Name=\"PublicEnumer" +
            "ationDeclaredInWorksheetInspection\" Severity=\"Warning\" InspectionType=\"NamingAnd" +
            "ConventionsIssues\" />\r\n    <CodeInspection Name=\"ReadOnlyPropertyAssignmentInspe" +
            "ction\" Severity=\"Error\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspecti" +
            "on Name=\"RedundantByRefModifierInspection\" Severity=\"DoNotShow\" InspectionType=\"" +
            "LanguageOpportunities\" />\r\n    <CodeInspection Name=\"RedundantOptionInspection\" " +
            "Severity=\"Hint\" InspectionType=\"LanguageOpportunities\" />\r\n    <CodeInspection N" +
            "ame=\"SelfAssignedDeclarationInspection\" Severity=\"Suggestion\" InspectionType=\"La" +
            "nguageOpportunities\" />\r\n    <CodeInspection Name=\"SetAssignmentWithIncompatible" +
            "ObjectTypeInspection\" Severity=\"Error\" InspectionType=\"CodeQualityIssues\" />\r\n  " +
            "  <CodeInspection Name=\"ShadowedDeclarationInspection\" Severity=\"DoNotShow\" Insp" +
            "ectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"SheetAccessedUsingS" +
            "tringInspection\" Severity=\"Suggestion\" InspectionType=\"LanguageOpportunities\" />" +
            "\r\n    <CodeInspection Name=\"StepIsNotSpecifiedInspection\" Severity=\"DoNotShow\" I" +
            "nspectionType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspection Name=\"StepOne" +
            "IsRedundantInspection\" Severity=\"Hint\" InspectionType=\"NamingAndConventionsIssue" +
            "s\" />\r\n    <CodeInspection Name=\"StopKeywordInspection\" Severity=\"Hint\" Inspecti" +
            "onType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"SuperfluousAnnotationAr" +
            "gumentInspection\" Severity=\"Warning\" InspectionType=\"RubberduckOpportunities\" />" +
            "\r\n    <CodeInspection Name=\"SuspiciousLetAssignmentInspection\" Severity=\"Error\" " +
            "InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"SuspiciousPrede" +
            "claredInstanceAccessInspection\" Severity=\"Warning\" InspectionType=\"CodeQualityIs" +
            "sues\" />\r\n    <CodeInspection Name=\"UDTMemberNotUsedInspection\" Severity=\"Sugges" +
            "tion\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"Unassigne" +
            "dVariableUsageInspection\" Severity=\"Error\" InspectionType=\"CodeQualityIssues\" />" +
            "\r\n    <CodeInspection Name=\"UndeclaredVariableInspection\" Severity=\"Error\" Inspe" +
            "ctionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"UnderscoreInPublicCl" +
            "assModuleMemberInspection\" Severity=\"Error\" InspectionType=\"CodeQualityIssues\" /" +
            ">\r\n    <CodeInspection Name=\"UnhandledOnErrorResumeNextInspection\" Severity=\"War" +
            "ning\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"Unreachab" +
            "leCaseInspection\" Severity=\"Warning\" InspectionType=\"CodeQualityIssues\" />\r\n    " +
            "<CodeInspection Name=\"UnrecognizedAnnotationInspection\" Severity=\"Warning\" Inspe" +
            "ctionType=\"RubberduckOpportunities\" />\r\n    <CodeInspection Name=\"UntypedFunctio" +
            "nUsageInspection\" Severity=\"Hint\" InspectionType=\"LanguageOpportunities\" />\r\n   " +
            " <CodeInspection Name=\"UseMeaningfulNameInspection\" Severity=\"Warning\" Inspectio" +
            "nType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspection Name=\"UseOfBangNotati" +
            "onInspection\" Severity=\"Hint\" InspectionType=\"NamingAndConventionsIssues\" />\r\n  " +
            "  <CodeInspection Name=\"UseOfRecursiveBangNotationInspection\" Severity=\"Suggesti" +
            "on\" InspectionType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspection Name=\"Us" +
            "eOfUnboundBangNotationInspection\" Severity=\"Warning\" InspectionType=\"NamingAndCo" +
            "nventionsIssues\" />\r\n    <CodeInspection Name=\"ValueRequiredInspection\" Severity" +
            "=\"Error\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"Variab" +
            "leNotAssignedInspection\" Severity=\"Error\" InspectionType=\"CodeQualityIssues\" />\r" +
            "\n    <CodeInspection Name=\"VariableNotUsedInspection\" Severity=\"Suggestion\" Insp" +
            "ectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"VariableTypeNotDecl" +
            "aredInspection\" Severity=\"Warning\" InspectionType=\"LanguageOpportunities\" />\r\n  " +
            "  <CodeInspection Name=\"WriteOnlyPropertyInspection\" Severity=\"Suggestion\" Inspe" +
            "ctionType=\"NamingAndConventionsIssues\" />\r\n  </CodeInspections>\r\n  <WhitelistedI" +
            "dentifiers />\r\n  <RunInspectionsOnSuccessfulParse>true</RunInspectionsOnSuccessf" +
            "ulParse>\r\n</CodeInspectionSettings>")]
        public global::Rubberduck.CodeAnalysis.Settings.CodeInspectionSettings CodeInspectionSettings {
            get {
                return ((global::Rubberduck.CodeAnalysis.Settings.CodeInspectionSettings)(this["CodeInspectionSettings"]));
            }
        }
    }
}
