//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubberduck.CodeAnalysis.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    public sealed partial class CodeInspectionDefaults : global::System.Configuration.ApplicationSettingsBase {
        
        private static CodeInspectionDefaults defaultInstance = ((CodeInspectionDefaults)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CodeInspectionDefaults())));
        
        public static CodeInspectionDefaults Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<CodeInspectionSettings xmlns:xsd=\"http:" +
            "//www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instanc" +
            "e\">\r\n  <CodeInspections>\r\n    <CodeInspection Name=\"AnnotationInIncompatibleComp" +
            "onentTypeInspection\" Severity=\"Warning\" InspectionType=\"RubberduckOpportunities\"" +
            " />\r\n    <CodeInspection Name=\"ApplicationWorksheetFunctionInspection\" Severity=" +
            "\"Suggestion\" InspectionType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspection" +
            " Name=\"ArgumentWithIncompatibleObjectTypeInspection\" Severity=\"Warning\" Inspecti" +
            "onType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspection Name=\"AssignedByValP" +
            "arameterInspection\" Severity=\"Warning\" InspectionType=\"CodeQualityIssues\" />\r\n  " +
            "  <CodeInspection Name=\"AssignmentNotUsedInspection\" Severity=\"Error\" Inspection" +
            "Type=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"AttributeValueOutOfSyncIn" +
            "spection\" Severity=\"Error\" InspectionType=\"RubberduckOpportunities\" />\r\n    <Cod" +
            "eInspection Name=\"BooleanAssignedInIfElseInspection\" Severity=\"Suggestion\" Inspe" +
            "ctionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ConstantNotUsedInspe" +
            "ction\" Severity=\"Warning\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspec" +
            "tion Name=\"DefaultMemberRequiredInspection\" Severity=\"Error\" InspectionType=\"Cod" +
            "eQualityIssues\" />\r\n    <CodeInspection Name=\"DefaultProjectNameInspection\" Seve" +
            "rity=\"Suggestion\" InspectionType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspe" +
            "ction Name=\"DefTypeStatementInspection\" Severity=\"Warning\" InspectionType=\"Langu" +
            "ageOpportunities\" />\r\n    <CodeInspection Name=\"DuplicatedAnnotationInspection\" " +
            "Severity=\"Error\" InspectionType=\"RubberduckOpportunities\" />\r\n    <CodeInspectio" +
            "n Name=\"EmptyCaseBlockInspection\" Severity=\"Hint\" InspectionType=\"CodeQualityIss" +
            "ues\" />\r\n    <CodeInspection Name=\"EmptyDoWhileBlockInspection\" Severity=\"Hint\" " +
            "InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"EmptyElseBlockI" +
            "nspection\" Severity=\"Hint\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspe" +
            "ction Name=\"EmptyForEachBlockInspection\" Severity=\"Hint\" InspectionType=\"CodeQua" +
            "lityIssues\" />\r\n    <CodeInspection Name=\"EmptyForLoopBlockInspection\" Severity=" +
            "\"Hint\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"EmptyIfB" +
            "lockInspection\" Severity=\"Hint\" InspectionType=\"CodeQualityIssues\" />\r\n    <Code" +
            "Inspection Name=\"EmptyMethodInspection\" Severity=\"Hint\" InspectionType=\"CodeQual" +
            "ityIssues\" />\r\n    <CodeInspection Name=\"EmptyModuleInspection\" Severity=\"Hint\" " +
            "InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"EmptyStringLite" +
            "ralInspection\" Severity=\"Suggestion\" InspectionType=\"LanguageOpportunities\" />\r\n" +
            "    <CodeInspection Name=\"EmptyWhileWendBlockInspection\" Severity=\"Hint\" Inspect" +
            "ionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"EncapsulatePublicField" +
            "Inspection\" Severity=\"Suggestion\" InspectionType=\"NamingAndConventionsIssues\" />" +
            "\r\n    <CodeInspection Name=\"ExcelMemberMayReturnNothingInspection\" Severity=\"War" +
            "ning\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ExcelUdfN" +
            "ameIsValidCellReferenceInspection\" Severity=\"Warning\" InspectionType=\"NamingAndC" +
            "onventionsIssues\" />\r\n    <CodeInspection Name=\"FunctionReturnValueAlwaysDiscard" +
            "edInspection\" Severity=\"Suggestion\" InspectionType=\"CodeQualityIssues\" />\r\n    <" +
            "CodeInspection Name=\"FunctionReturnValueDiscardedInspection\" Severity=\"Hint\" Ins" +
            "pectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"HostSpecificExpres" +
            "sionInspection\" Severity=\"Warning\" InspectionType=\"CodeQualityIssues\" />\r\n    <C" +
            "odeInspection Name=\"HungarianNotationInspection\" Severity=\"Suggestion\" Inspectio" +
            "nType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspection Name=\"IIfSideEffectIn" +
            "spection\" Severity=\"Error\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspe" +
            "ction Name=\"ImplementedInterfaceMemberInspection\" Severity=\"Warning\" InspectionT" +
            "ype=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ImplicitActiveSheetReferen" +
            "ceInspection\" Severity=\"Warning\" InspectionType=\"CodeQualityIssues\" />\r\n    <Cod" +
            "eInspection Name=\"ImplicitActiveWorkbookReferenceInspection\" Severity=\"Warning\" " +
            "InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ImplicitByRefMo" +
            "difierInspection\" Severity=\"Hint\" InspectionType=\"NamingAndConventionsIssues\" />" +
            "\r\n    <CodeInspection Name=\"ImplicitContainingWorkbookReferenceInspection\" Sever" +
            "ity=\"Warning\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"I" +
            "mplicitContainingWorksheetReferenceInspection\" Severity=\"Warning\" InspectionType" +
            "=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ImplicitDefaultMemberAccessIn" +
            "spection\" Severity=\"Warning\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeIns" +
            "pection Name=\"ImplicitlyTypedConstInspection\" Severity=\"Warning\" InspectionType=" +
            "\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ImplicitPublicMemberInspection" +
            "\" Severity=\"Hint\" InspectionType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspe" +
            "ction Name=\"ImplicitRecursiveDefaultMemberAccessInspection\" Severity=\"Suggestion" +
            "\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ImplicitUnbou" +
            "ndDefaultMemberAccessInspection\" Severity=\"Warning\" InspectionType=\"CodeQualityI" +
            "ssues\" />\r\n    <CodeInspection Name=\"ImplicitVariantReturnTypeInspection\" Severi" +
            "ty=\"Warning\" InspectionType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspection" +
            " Name=\"InconsistentArrayBaseInspection\" Severity=\"Hint\" InspectionType=\"CodeQual" +
            "ityIssues\" />\r\n    <CodeInspection Name=\"InconsistentParamArrayBaseInspection\" S" +
            "everity=\"Hint\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"" +
            "IndexedDefaultMemberAccessInspection\" Severity=\"Hint\" InspectionType=\"NamingAndC" +
            "onventionsIssues\" />\r\n    <CodeInspection Name=\"IndexedRecursiveDefaultMemberAcc" +
            "essInspection\" Severity=\"Suggestion\" InspectionType=\"NamingAndConventionsIssues\"" +
            " />\r\n    <CodeInspection Name=\"IndexedUnboundDefaultMemberAccessInspection\" Seve" +
            "rity=\"Warning\" InspectionType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspecti" +
            "on Name=\"IntegerDataTypeInspection\" Severity=\"Suggestion\" InspectionType=\"Langua" +
            "geOpportunities\" />\r\n    <CodeInspection Name=\"InvalidAnnotationInspection\" Seve" +
            "rity=\"Warning\" InspectionType=\"RubberduckOpportunities\" />\r\n    <CodeInspection " +
            "Name=\"IsMissingOnInappropriateArgumentInspection\" Severity=\"Error\" InspectionTyp" +
            "e=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"IsMissingWithNonArgumentPara" +
            "meterInspection\" Severity=\"Error\" InspectionType=\"CodeQualityIssues\" />\r\n    <Co" +
            "deInspection Name=\"KeywordsUsedAsMemberInspection\" Severity=\"Warning\" Inspection" +
            "Type=\"NamingAndConventionsIssues\" />\r\n    <CodeInspection Name=\"LineContinuation" +
            "BetweenKeywordsInspection\" Severity=\"Error\" InspectionType=\"NamingAndConventions" +
            "Issues\" />\r\n    <CodeInspection Name=\"LineLabelNotUsedInspection\" Severity=\"Sugg" +
            "estion\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"MemberN" +
            "otOnInterfaceInspection\" Severity=\"Warning\" InspectionType=\"CodeQualityIssues\" /" +
            ">\r\n    <CodeInspection Name=\"MisleadingByRefInspection\" Severity=\"Warning\" Inspe" +
            "ctionType=\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"MissingAnnotatio" +
            "nArgumentInspection\" Severity=\"Error\" InspectionType=\"RubberduckOpportunities\" /" +
            ">\r\n    <CodeInspection Name=\"MissingAttributeInspection\" Severity=\"Error\" Inspec" +
            "tionType=\"RubberduckOpportunities\" />\r\n    <CodeInspection Name=\"MissingMemberAn" +
            "notationInspection\" Severity=\"Warning\" InspectionType=\"RubberduckOpportunities\" " +
            "/>\r\n    <CodeInspection Name=\"MissingModuleAnnotationInspection\" Severity=\"Warni" +
            "ng\" InspectionType=\"RubberduckOpportunities\" />\r\n    <CodeInspection Name=\"Modul" +
            "eScopeDimKeywordInspection\" Severity=\"Suggestion\" InspectionType=\"NamingAndConve" +
            "ntionsIssues\" />\r\n    <CodeInspection Name=\"ModuleWithoutFolderInspection\" Sever" +
            "ity=\"Suggestion\" InspectionType=\"RubberduckOpportunities\" />\r\n    <CodeInspectio" +
            "n Name=\"MoveFieldCloserToUsageInspection\" Severity=\"Suggestion\" InspectionType=\"" +
            "NamingAndConventionsIssues\" />\r\n    <CodeInspection Name=\"MultilineParameterInsp" +
            "ection\" Severity=\"Warning\" InspectionType=\"NamingAndConventionsIssues\" />\r\n    <" +
            "CodeInspection Name=\"MultipleDeclarationsInspection\" Severity=\"Warning\" Inspecti" +
            "onType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspection Name=\"NegativeLineNu" +
            "mberInspection\" Severity=\"Warning\" InspectionType=\"CodeQualityIssues\" />\r\n    <C" +
            "odeInspection Name=\"NonBreakingSpaceIdentifierInspection\" Severity=\"Warning\" Ins" +
            "pectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"NonReturningFuncti" +
            "onInspection\" Severity=\"Error\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeI" +
            "nspection Name=\"ObjectVariableNotSetInspection\" Severity=\"Error\" InspectionType=" +
            "\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ObjectWhereProcedureIsRequired" +
            "Inspection\" Severity=\"Error\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeIns" +
            "pection Name=\"ObsoleteCallingConventionInspection\" Severity=\"Error\" InspectionTy" +
            "pe=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ObsoleteCallStatementInspec" +
            "tion\" Severity=\"Suggestion\" InspectionType=\"LanguageOpportunities\" />\r\n    <Code" +
            "Inspection Name=\"ObsoleteCommentSyntaxInspection\" Severity=\"Suggestion\" Inspecti" +
            "onType=\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"ObsoleteErrorSyntax" +
            "Inspection\" Severity=\"Suggestion\" InspectionType=\"LanguageOpportunities\" />\r\n   " +
            " <CodeInspection Name=\"ObsoleteGlobalInspection\" Severity=\"Suggestion\" Inspectio" +
            "nType=\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"ObsoleteLetStatement" +
            "Inspection\" Severity=\"Suggestion\" InspectionType=\"LanguageOpportunities\" />\r\n   " +
            " <CodeInspection Name=\"ObsoleteMemberUsageInspection\" Severity=\"Warning\" Inspect" +
            "ionType=\"RubberduckOpportunities\" />\r\n    <CodeInspection Name=\"ObsoleteTypeHint" +
            "Inspection\" Severity=\"Suggestion\" InspectionType=\"LanguageOpportunities\" />\r\n   " +
            " <CodeInspection Name=\"ObsoleteWhileWendStatementInspection\" Severity=\"Suggestio" +
            "n\" InspectionType=\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"OnErrorG" +
            "oToMinusOneInspection\" Severity=\"Suggestion\" InspectionType=\"LanguageOpportuniti" +
            "es\" />\r\n    <CodeInspection Name=\"OnLocalErrorInspection\" Severity=\"Suggestion\" " +
            "InspectionType=\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"OptionBaseI" +
            "nspection\" Severity=\"Hint\" InspectionType=\"NamingAndConventionsIssues\" />\r\n    <" +
            "CodeInspection Name=\"OptionExplicitInspection\" Severity=\"Error\" InspectionType=\"" +
            "NamingAndConventionsIssues\" />\r\n    <CodeInspection Name=\"ParameterCanBeByValIns" +
            "pection\" Severity=\"Suggestion\" InspectionType=\"LanguageOpportunities\" />\r\n    <C" +
            "odeInspection Name=\"ParameteressCellsInspection\" Severity=\"Suggestion\" Inspectio" +
            "nType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ParameterNotUsedInspecti" +
            "on\" Severity=\"Suggestion\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspec" +
            "tion Name=\"ProcedureCanBeWrittenAsFunctionInspection\" Severity=\"Suggestion\" Insp" +
            "ectionType=\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"ProcedureNotUse" +
            "dInspection\" Severity=\"Suggestion\" InspectionType=\"CodeQualityIssues\" />\r\n    <C" +
            "odeInspection Name=\"ProcedureRequiredInspection\" Severity=\"Error\" InspectionType" +
            "=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"PublicControlFieldAccessInspe" +
            "ction\" Severity=\"Hint\" InspectionType=\"NamingAndConventionsIssues\" />\r\n    <Code" +
            "Inspection Name=\"PublicEnumerationDeclaredInWorksheetInspection\" Severity=\"Warni" +
            "ng\" InspectionType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspection Name=\"Re" +
            "adOnlyPropertyAssignmentInspection\" Severity=\"Error\" InspectionType=\"CodeQuality" +
            "Issues\" />\r\n    <CodeInspection Name=\"RedundantByRefModifierInspection\" Severity" +
            "=\"DoNotShow\" InspectionType=\"LanguageOpportunities\" />\r\n    <CodeInspection Name" +
            "=\"RedundantOptionInspection\" Severity=\"Hint\" InspectionType=\"LanguageOpportuniti" +
            "es\" />\r\n    <CodeInspection Name=\"SelfAssignedDeclarationInspection\" Severity=\"S" +
            "uggestion\" InspectionType=\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"" +
            "SetAssignmentWithIncompatibleObjectTypeInspection\" Severity=\"Error\" InspectionTy" +
            "pe=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"ShadowedDeclarationInspecti" +
            "on\" Severity=\"DoNotShow\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspect" +
            "ion Name=\"SheetAccessedUsingStringInspection\" Severity=\"Suggestion\" InspectionTy" +
            "pe=\"LanguageOpportunities\" />\r\n    <CodeInspection Name=\"StepIsNotSpecifiedInspe" +
            "ction\" Severity=\"DoNotShow\" InspectionType=\"NamingAndConventionsIssues\" />\r\n    " +
            "<CodeInspection Name=\"StepOneIsRedundantInspection\" Severity=\"Hint\" InspectionTy" +
            "pe=\"NamingAndConventionsIssues\" />\r\n    <CodeInspection Name=\"StopKeywordInspect" +
            "ion\" Severity=\"Hint\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection " +
            "Name=\"SuperfluousAnnotationArgumentInspection\" Severity=\"Warning\" InspectionType" +
            "=\"RubberduckOpportunities\" />\r\n    <CodeInspection Name=\"SuspiciousLetAssignment" +
            "Inspection\" Severity=\"Error\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeIns" +
            "pection Name=\"SuspiciousPredeclaredInstanceAccessInspection\" Severity=\"Warning\" " +
            "InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"UDTMemberNotUse" +
            "dInspection\" Severity=\"Suggestion\" InspectionType=\"CodeQualityIssues\" />\r\n    <C" +
            "odeInspection Name=\"UnassignedVariableUsageInspection\" Severity=\"Error\" Inspecti" +
            "onType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"UndeclaredVariableInspe" +
            "ction\" Severity=\"Error\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspecti" +
            "on Name=\"UnderscoreInPublicClassModuleMemberInspection\" Severity=\"Error\" Inspect" +
            "ionType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"UnhandledOnErrorResume" +
            "NextInspection\" Severity=\"Warning\" InspectionType=\"CodeQualityIssues\" />\r\n    <C" +
            "odeInspection Name=\"UnreachableCaseInspection\" Severity=\"Warning\" InspectionType" +
            "=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"UnrecognizedAnnotationInspect" +
            "ion\" Severity=\"Warning\" InspectionType=\"RubberduckOpportunities\" />\r\n    <CodeIn" +
            "spection Name=\"UntypedFunctionUsageInspection\" Severity=\"Hint\" InspectionType=\"L" +
            "anguageOpportunities\" />\r\n    <CodeInspection Name=\"UseMeaningfulNameInspection\"" +
            " Severity=\"Warning\" InspectionType=\"NamingAndConventionsIssues\" />\r\n    <CodeIns" +
            "pection Name=\"UseOfBangNotationInspection\" Severity=\"Hint\" InspectionType=\"Namin" +
            "gAndConventionsIssues\" />\r\n    <CodeInspection Name=\"UseOfRecursiveBangNotationI" +
            "nspection\" Severity=\"Suggestion\" InspectionType=\"NamingAndConventionsIssues\" />\r" +
            "\n    <CodeInspection Name=\"UseOfUnboundBangNotationInspection\" Severity=\"Warning" +
            "\" InspectionType=\"NamingAndConventionsIssues\" />\r\n    <CodeInspection Name=\"Valu" +
            "eRequiredInspection\" Severity=\"Error\" InspectionType=\"CodeQualityIssues\" />\r\n   " +
            " <CodeInspection Name=\"VariableNotAssignedInspection\" Severity=\"Error\" Inspectio" +
            "nType=\"CodeQualityIssues\" />\r\n    <CodeInspection Name=\"VariableNotUsedInspectio" +
            "n\" Severity=\"Suggestion\" InspectionType=\"CodeQualityIssues\" />\r\n    <CodeInspect" +
            "ion Name=\"VariableTypeNotDeclaredInspection\" Severity=\"Warning\" InspectionType=\"" +
            "LanguageOpportunities\" />\r\n    <CodeInspection Name=\"WriteOnlyPropertyInspection" +
            "\" Severity=\"Suggestion\" InspectionType=\"NamingAndConventionsIssues\" />\r\n  </Code" +
            "Inspections>\r\n  <WhitelistedIdentifiers />\r\n  <RunInspectionsOnSuccessfulParse>t" +
            "rue</RunInspectionsOnSuccessfulParse>\r\n  <IgnoreFormControlsHungarianNotation>tr" +
            "ue</IgnoreFormControlsHungarianNotation>\r\n</CodeInspectionSettings>")]
        public global::Rubberduck.CodeAnalysis.Settings.CodeInspectionSettings CodeInspectionSettings {
            get {
                return ((global::Rubberduck.CodeAnalysis.Settings.CodeInspectionSettings)(this["CodeInspectionSettings"]));
            }
        }
    }
}
